name: Publish Docker image

on:
  push:
    branches:
      - test-build
  # release:
  #   types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Runpod instance
        id: start_runpod
        env:
          RUNPOD_API_TOKEN: ${{ secrets.RUNPOD_API_TOKEN }}
        run: |
          GPU_TYPE="NVIDIA GeForce RTX 4070 Ti"
          IMAGE_NAME="runpod/ubuntu:22.04"

          START_RESPONSE=$(curl \
            --silent
            --request POST \
            --header 'content-type: application/json' \
            --url "https://api.runpod.io/graphql?api_key=$RUNPOD_API_TOKEN" \
            --data-raw $'{
              "operationName":"Mutation",
              "variables":{"input":{"instanceId":"cpu3c-16-32","cloudType":"SECURE","containerDiskInGb":5,"deployCost":0.48,"dataCenterId":null,"networkVolumeId":null,"startJupyter":true,"startSsh":true,"templateId":"runpod-ubuntu","volumeKey":null,"ports":"22/tcp"}},
              "query":"mutation Mutation($input: deployCpuPodInput\u0021) {\\n  deployCpuPod(input: $input) {\\n    id\\n    imageName\\n    env\\n    machineId\\n    machine {\\n      podHostId\\n      __typename\\n    }\\n    __typename\\n  }\\n}"
            }')

          # echo $START_RESPONSE

          INSTANCE_ID=$(echo $START_RESPONSE | jq -r '.data.deployCpuPod.id')
          echo $INSTANCE_ID
          echo "instance_id=$INSTANCE_ID" >> "$GITHUB_OUTPUT"

      - name: Wait for Runpod instance to be ready
        env:
          RUNPOD_API_TOKEN: ${{ secrets.RUNPOD_API_TOKEN }}
        run: |

          echo "${{ steps.start_runpod.outputs.instance_id }}"

          INSTANCE_ID="${{ steps.start_runpod.outputs.instance_id }}"
          while true; do
            STATUS_RESPONSE=$(curl  \
              --silent
              --request POST \
              --header 'content-type: application/json' \
              --url "https://api.runpod.io/graphql?api_key=$RUNPOD_API_TOKEN" \
              --data-raw '{"operationName":"myPods","variables":{},"query":"query myPods {\n  myself {\n    id\n    clientBalance\n    savingsPlans {\n      startTime\n      endTime\n      gpuTypeId\n      podId\n      costPerHr\n      __typename\n    }\n    pods {\n      savingsPlans {\n        gpuTypeId\n        endTime\n        costPerHr\n        __typename\n      }\n      containerDiskInGb\n      containerRegistryAuthId\n      costPerHr\n      adjustedCostPerHr\n      desiredStatus\n      dockerArgs\n      dockerId\n      env\n      gpuCount\n      id\n      imageName\n      lastStatusChange\n      locked\n      machineId\n      memoryInGb\n      name\n      networkVolume {\n        id\n        name\n        size\n        __typename\n      }\n      cpuFlavorId\n      machineType\n      cpuFlavor {\n        groupName\n        displayName\n        __typename\n      }\n      podType\n      port\n      ports\n      templateId\n      uptimeSeconds\n      vcpuCount\n      version\n      volumeEncrypted\n      volumeInGb\n      volumeMountPath\n      machine {\n        costPerHr\n        currentPricePerGpu\n        diskMBps\n        gpuAvailable\n        gpuDisplayName\n        location\n        maintenanceEnd\n        maintenanceNote\n        maintenanceStart\n        minPodGpuCount\n        maxDownloadSpeedMbps\n        maxUploadSpeedMbps\n        note\n        podHostId\n        secureCloud\n        supportPublicIp\n        gpuTypeId\n        gpuType {\n          secureSpotPrice\n          communitySpotPrice\n          oneMonthPrice\n          threeMonthPrice\n          sixMonthPrice\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}"}'
            )

            STATUS=$(echo $RESPONSE | jq -r ".data.myself.pods[] | select(.id==\"$INSTANCE_ID\") | .desiredStatus")

            echo $STATUS

            if [ "$STATUS" == "RUNNING" ]; then
              echo "Instance is running."
              break
            else
              echo "Waiting for instance to be ready..."
              sleep 10
            fi
          done

      # - name: Get Runpod instance SSH details
      #   id: get_ssh_details
      #   env:
      #     RUNPOD_API_TOKEN: ${{ secrets.RUNPOD_API_TOKEN }}
      #   run: |
      #     INSTANCE_ID="${{ steps.start_runpod.outputs.instance_id }}"
      #     SSH_RESPONSE=$(curl -s -X GET "https://api.runpod.io/instance/$INSTANCE_ID/ssh" \
      #       -H "Authorization: Bearer $RUNPOD_API_TOKEN")
      #     SSH_HOST=$(echo $SSH_RESPONSE | jq -r '.host')
      #     SSH_USER=$(echo $SSH_RESPONSE | jq -r '.user')
      #     SSH_KEY=$(echo $SSH_RESPONSE | jq -r '.key')
      #     echo "$SSH_KEY" > runpod_ssh_key
      #     chmod 600 runpod_ssh_key
      #     echo "::set-output name=ssh_host::$SSH_HOST"
      #     echo "::set-output name=ssh_user::$SSH_USER"

      # - name: SSH and run commands on Runpod instance
      #   env:
      #     REPOSITORY: ${{ github.repository }}
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      #   run: |
      #     SSH_HOST="${{ steps.get_ssh_details.outputs.ssh_host }}"
      #     SSH_USER="${{ steps.get_ssh_details.outputs.ssh_user }}"
      #     ssh -i runpod_ssh_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
      #       git clone https://github.com/$REPOSITORY.git
      #       cd $(basename "$REPOSITORY")
      #       VERSION=$(python -c "import ai_diffusion; print(ai_diffusion.__version__)")
      #       pip install -r requirements.txt
      #       python scripts/docker.py
      #       docker build -t $DOCKERHUB_USERNAME/$(basename "$REPOSITORY"):$VERSION scripts/docker
      #       echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      #       docker push $DOCKERHUB_USERNAME/$(basename "$REPOSITORY"):$VERSION
      #     EOF

      # - name: Terminate Runpod instance
      #   run: |
      #     INSTANCE_ID="${{ steps.start_runpod.outputs.instance_id }}"
      #     RUNPOD_API_TOKEN="YOUR_RUNPOD_API_TOKEN"
      #     curl -s -X POST "https://api.runpod.io/instance/$INSTANCE_ID/terminate" \
      #       -H "Authorization: Bearer $RUNPOD_API_TOKEN" \
      #       -H "Content-Type: application/json"
